Fix gate along with failed py27 and pep8
astara-neutron raised issue when import wrong package as following: 

ImportError: cannot import name model_base

Thus this gate depend on astara-neutron PS to fix done.

Depends-On: I75b6979b3c611a28608aed5c3e4d5658ff3bffea

Change-Id: I14351ae04d47c1c1a827cc49f28125e1d4cdc090